export const TITLES = [
  { id: 1, name: "Stranger Things", type: "series", image: "https://image.tmdb.org/t/p/w200/x2LSRK2Cm7MZhjluni1msVJ3wDF.jpg" },
  { id: 2, name: "The Witcher", type: "series", image: "https://image.tmdb.org/t/p/w200/zrPpUlehQaBf8YX2NrVrKK8IEpf.jpg" },
  { id: 3, name: "Breaking Bad", type: "series", image: "https://image.tmdb.org/t/p/w200/ggFHVNu6YYI5L9pCfOacjizRGt.jpg" },
  { id: 4, name: "Game of Thrones", type: "series", image: "https://image.tmdb.org/t/p/w200/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg" },
  { id: 5, name: "Black Mirror", type: "series", image: "https://image.tmdb.org/t/p/w200/pHkKbIRoCe7zIFvqan9LFSaQAde.jpg" },
  { id: 6, name: "The Crown", type: "series", image: "https://image.tmdb.org/t/p/w200/izg2Yl0uFvYtVx0c0Bz3e8AAf7K.jpg" },
  { id: 7, name: "Dune: Part Two", type: "movie", image: "https://image.tmdb.org/t/p/w200/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg" },
  { id: 8, name: "Oppenheimer", type: "movie", image: "https://image.tmdb.org/t/p/w200/bAQ8O5Uw6FedtlCbJTutenzPVKd.jpg" },
  { id: 9, name: "Barbie", type: "movie", image: "https://image.tmdb.org/t/p/w200/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg" },
  { id: 10, name: "Inception", type: "movie", image: "https://image.tmdb.org/t/p/w200/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg" },
  { id: 11, name: "The Dark Knight", type: "movie", image: "https://image.tmdb.org/t/p/w200/qJ2tW6WMUDux911r6m7haRef0WH.jpg" },
  { id: 12, name: "Interstellar", type: "movie", image: "https://image.tmdb.org/t/p/w200/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg" },
  { id: 13, name: "Avatar: The Way of Water", type: "movie", image: "https://image.tmdb.org/t/p/w200/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg" },
  { id: 14, name: "The Last of Us", type: "series", image: "https://image.tmdb.org/t/p/w200/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg" },
  { id: 15, name: "Squid Game", type: "series", image: "https://image.tmdb.org/t/p/w200/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg" },
  { id: 16, name: "The Mandalorian", type: "series", image: "https://image.tmdb.org/t/p/w200/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg" },
  { id: 17, name: "Everything Everywhere All at Once", type: "movie", image: "https://image.tmdb.org/t/p/w200/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg" },
  { id: 18, name: "Parasite", type: "movie", image: "https://image.tmdb.org/t/p/w200/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg" },
  { id: 19, name: "Severance", type: "series", image: "https://image.tmdb.org/t/p/w200/jeEe6uOZ1kyW5kXbqzjVJwO4bF3.jpg" },
  { id: 20, name: "Blade Runner 2049", type: "movie", image: "https://image.tmdb.org/t/p/w200/aMpyrCizvS5P3kz0H4rGNAgsWKM.jpg" },
  { id: 21, name: "The Boys", type: "series", image: "https://image.tmdb.org/t/p/w200/mY7SeH4HFFxW1hiI6cWuwCRKptN.jpg" },
  { id: 22, name: "Better Call Saul", type: "series", image: "https://image.tmdb.org/t/p/w200/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg" },
  { id: 23, name: "House of the Dragon", type: "series", image: "https://image.tmdb.org/t/p/w200/7QpkS4zWbVh8xJWrckAozzQdHqk.jpg" },
  { id: 24, name: "The Matrix", type: "movie", image: "https://image.tmdb.org/t/p/w200/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg" },
  { id: 25, name: "The Matrix Resurrections", type: "movie", image: "https://image.tmdb.org/t/p/w200/8c4a8kE7PizaGQQnditMmI1xbRp.jpg" },
  { id: 26, name: "Cyberpunk: Edgerunners", type: "series", image: "https://image.tmdb.org/t/p/w200/qI1QNeD1cihxlHXLl0f1IZRfMTD.jpg" },
  { id: 27, name: "Attack on Titan", type: "series", image: "https://image.tmdb.org/t/p/w200/sHim7O6j2WcnIYtFCcd2HcKtGgY.jpg" },
  { id: 28, name: "Demon Slayer: Kimetsu no Yaiba", type: "series", image: "https://image.tmdb.org/t/p/w200/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg" },
  { id: 29, name: "Jujutsu Kaisen", type: "series", image: "https://image.tmdb.org/t/p/w200/3fl1Hafo7OxQ2Q6aL6xykz5kj4E.jpg" },
  { id: 30, name: "One Piece", type: "series", image: "https://image.tmdb.org/t/p/w200/6YNxZ2QHGlhJ48zjJk0K7ahEzzN.jpg" },
  { id: 31, name: "Arcane", type: "series", image: "https://image.tmdb.org/t/p/w200/vk2ZxEW9x2M0CkZbK71F1PSLDZl.jpg" },
  { id: 32, name: "The Office", type: "series", image: "https://image.tmdb.org/t/p/w200/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg" },
  { id: 33, name: "Friends", type: "series", image: "https://image.tmdb.org/t/p/w200/f496cm9enuEsZkSPzCwnTESEK5s.jpg" },
  { id: 34, name: "The Social Network", type: "movie", image: "https://image.tmdb.org/t/p/w200/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg" },
  { id: 35, name: "Ex Machina", type: "movie", image: "https://image.tmdb.org/t/p/w200/btbRB7BrD887j5NrvjxafFYyja7.jpg" },
  { id: 36, name: "Her", type: "movie", image: "https://image.tmdb.org/t/p/w200/eCOtqtfvn7mxGl6nfmq4b1exJRc.jpg" },
  { id: 37, name: "The Grand Budapest Hotel", type: "movie", image: "https://image.tmdb.org/t/p/w200/nX5XotM9yprCKarRH4fzOq1VM1J.jpg" },
  { id: 38, name: "La La Land", type: "movie", image: "https://image.tmdb.org/t/p/w200/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg" },
  { id: 39, name: "Whiplash", type: "movie", image: "https://image.tmdb.org/t/p/w200/lIv1QinFqz4dlp5U4lQ6HaiskOZ.jpg" },
  { id: 40, name: "The Good Place", type: "series", image: "https://image.tmdb.org/t/p/w200/ba4cpvnaxvAgux7D6E3lHGnMRZX.jpg" },
  { id: 41, name: "Ted Lasso", type: "series", image: "https://image.tmdb.org/t/p/w200/5V4XUqR6Isd3S3C6yJrZkT37CxU.jpg" },
  { id: 42, name: "Succession", type: "series", image: "https://image.tmdb.org/t/p/w200/7c0E9M2C0BjEoXzA1rZoqjXz0hL.jpg" },
  { id: 43, name: "Peaky Blinders", type: "series", image: "https://image.tmdb.org/t/p/w200/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg" },
  { id: 44, name: "Mindhunter", type: "series", image: "https://image.tmdb.org/t/p/w200/fbj2YfT1gCzqLez5nUZT33ypdG4.jpg" },
  { id: 45, name: "Mr. Robot", type: "series", image: "https://image.tmdb.org/t/p/w200/oKIBhzZzDX07SoE2bOLhq2EE8rf.jpg" },
  { id: 46, name: "Narcos", type: "series", image: "https://image.tmdb.org/t/p/w200/rTmal9fDbwh5F0waol2hq35U4ah.jpg" },
  { id: 47, name: "Money Heist", type: "series", image: "https://image.tmdb.org/t/p/w200/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg" },
  { id: 48, name: "The Queen's Gambit", type: "series", image: "https://image.tmdb.org/t/p/w200/zU0htwkhNvBQdVSIKB9s6hgVeFK.jpg" },
  { id: 49, name: "Wednesday", type: "series", image: "https://image.tmdb.org/t/p/w200/9PFonBhy4cQy7Jz20NpMygczOkv.jpg" },
  { id: 50, name: "The Umbrella Academy", type: "series", image: "https://image.tmdb.org/t/p/w200/uYHdIs5O8tiU5p6MvUPd2jElOH6.jpg" },
  { id: 51, name: "The Batman", type: "movie", image: "https://image.tmdb.org/t/p/w200/74xTEgt7R36Fpooo50r9T25onhq.jpg" },
  { id: 52, name: "Tenet", type: "movie", image: "https://image.tmdb.org/t/p/w200/k68nPLbIST6NP96JmTxmZijEvCA.jpg" },
  { id: 53, name: "Joker", type: "movie", image: "https://image.tmdb.org/t/p/w200/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg" },
  { id: 54, name: "1917", type: "movie", image: "https://image.tmdb.org/t/p/w200/iZf0KyrE25z1sage4SYFLCCrMi9.jpg" },
  { id: 55, name: "Dunkirk", type: "movie", image: "https://image.tmdb.org/t/p/w200/ebSnODDg9lbsMIaWg2uAbjn7TO5.jpg" },
  { id: 56, name: "Mad Max: Fury Road", type: "movie", image: "https://image.tmdb.org/t/p/w200/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg" },
  { id: 57, name: "Arrival", type: "movie", image: "https://image.tmdb.org/t/p/w200/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg" },
  { id: 58, name: "The Handmaid's Tale", type: "series", image: "https://image.tmdb.org/t/p/w200/oIkxqt6ug5zT5ZSUUyc1Iqopf02.jpg" },
  { id: 59, name: "Westworld", type: "series", image: "https://image.tmdb.org/t/p/w200/y55oBgf6bVMI7sFNXwJDrSIxPQt.jpg" },
  { id: 60, name: "The Expanse", type: "series", image: "https://image.tmdb.org/t/p/w200/k2K8R2n3U3bD0E9bK6phgZg1VtV.jpg" }
];
